### PR TITLE
Login_page fixed 

### LINKED ISSUE #23: Fix the login page
image

The login page is totally broken. I had implemented a simple login page before but it somehow got messed due to other contributor actiivity. It's time to fix it.

**task:** The input fields should be clear and visible

### PR DESCRIPTION
**Pull request by Tushar98644**
closes #23

### CODE REVIEW

**Comment by aritroCoder** [comment]
image
see, it is still not what I wanted.
Make the size of the box bigger 
Fix the overlap of the elements

**Comment by Tushar98644** [comment]
> image see, it is still not what I wanted. Make the size of the box bigger Fix the overlap of the elements

this pr was for the login form ....not the login profile page

**Comment by Tushar98644** [comment]
> image see, it is still not what I wanted. Make the size of the box bigger Fix the overlap of the elements
> 
> just a suggestion: using single values for margin, padding or width will cause these kind of issues, try to use media queries where you will give some width for desktop and other width for mobile devices

ya will keep in mind while solving the issue ....

**Comment by aritroCoder** [comment]
> > image see, it is still not what I wanted. Make the size of the box bigger Fix the overlap of the elements
> 
> this pr was for the login form ....not the login profile page

Ok, my bad. I am reviewing so many issues it sometimes become confusing

**Comment by Tushar98644** [comment]
> > > image see, it is still not what I wanted. Make the size of the box bigger Fix the overlap of the elements
> > 
> > 
> > this pr was for the login form ....not the login profile page
> 
> Ok, my bad. I am reviewing so many issues it sometimes become confusing

ya ik...it is hard for mentors to review so many issues ....thnx for always reviewing them in time

**Comment by aritroCoder** [comment]
image
Too much whitespace left unused, make the elements bigger

**Comment by Tushar98644** [comment]
> image Too much whitespace left unused, make the elements bigger

ok....

**Comment by Tushar98644** [comment]
fixed @aritroCoder

**Comment by aritroCoder** [comment]
image

Just compare the text size generated by chrome suggestions and the login inputs. The suggestion text is a good example of what looks clear in a phone display. Small components are not touch friendly in small displays. As I said you need to define CSS sizes for desktop, tablet and mobile seperately.

**Comment by Tushar98644** [comment]
> image
> 
> Just compare the text size generated by chrome suggestions and the login inputs. The suggestion text is a good example of what looks clear in a phone display. Small components are not touch friendly in small displays. As I said you need to define CSS sizes for desktop, tablet and mobile seperately.

ok ...will do so and complete tomorrow...

**Pull request closed without merging**
