### PR TITLE
Hamburger menu created on navabar

### PR DESCRIPTION
**Pull request by Tushar98644**
Screenshot 2022-12-29 at 11 48 28 AM

### CODE REVIEW

**Comment by aritroCoder** [comment]
This is not what I meant. The menu should only be there in mobile screens, where the navbar is too small to fit. 


image
This is a sample image of what I want.


In desktop mode the original navbar works well

**Comment by Tushar98644** [comment]
> This is not what I meant. The menu should only be there in mobile screens, where the navbar is too small to fit.
> 
> image This is a sample image of what I want.
> 
> In desktop mode the original navbar works well

changes made....

https://user-images.githubusercontent.com/107763774/209922985-2f15e2c8-2423-4a27-afc9-fa821d6c54f6.mov

**Comment by aritroCoder** [comment]
and make sure the menu items in the hamburger menu are same as the original nav

**Comment by Tushar98644** [comment]
> and make sure the menu items in the hamburger menu are same as the original nav

Ya i have kept the items same .....made changes with the 3rd commit

**Comment by aritroCoder** [comment]
Ok, looks fine to me
closes #22 
Thanks for the PR

**Comment by Tushar98644** [comment]
> Ok, looks fine to me closes #22 Thanks for the PR

haven't received points for the pr....

**Comment by aritroCoder** [comment]
> > Ok, looks fine to me closes #22 Thanks for the PR
> 
> haven't received points for the pr....

added

**Comment by aritroCoder** [comment]
5 + 15 points awarded

**Comment by Tushar98644** [comment]
> 5 + 15 points awarded

ya thnx a lot....

new pr created ...pls check

**Pull request merged**
