### PR TITLE
Responsive About us page created 

### PR DESCRIPTION
**Pull request by Tushar98644**
https://user-images.githubusercontent.com/107763774/209567115-901a0c65-fb6e-46cd-9cc2-38e567e492d5.mp4

### CODE REVIEW

**Comment by Tushar98644** [comment]
closes #4 

@aritroCoder

**Comment by aritroCoder** [comment]
wow great design! I'll merge it

**Comment by Tushar98644** [comment]
> wow great design! I'll merge it

thnx....can you generate some more issues to work on?basically all other issues are assigned😅 ..

**Comment by aritroCoder** [comment]
> > wow great design! I'll merge it
> 
> thnx....can you generate some more issues to work on?basically all other issues are assignedsweat_smile ..

Okay, I will create new issues by tommorrow

**Comment by Tushar98644** [comment]
> > > wow great design! I'll merge it
> > 
> > 
> > thnx....can you generate some more issues to work on?basically all other issues are assignedsweat_smile ..
> 
> Okay, I will create new issues by tommorrow

thnx ...

**Pull request merged**
