### PR TITLE
blog_page created 

### PR DESCRIPTION
**Pull request by Tushar98644**
Screenshot 2022-12-29 at 8 39 08 PM

### CODE REVIEW

**Comment by aritroCoder** [comment]
Few improvement suggestions:
1. for desktop view, add a margin to the left as it appears to be sticking to the left
2. both side margin is needed in mobile view. Might even try to fix aspect ratio of images as they look quite distorted. 
image

3. For dimentions less than 600px(width), the page looks like this: 
image
This issue did not occur during the navbar PR where I checked the hamburger nav, but it is only occuring in this specific page in the website. 

FIx these issues and tell me for another review

**Comment by aritroCoder** [comment]
another thing, you are using bootstrap in this website, as evident from the line in `_app.js` file
```javascript
  useEffect(() => {
    require("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
```
but you never seem to install the bootstrap packages via npm (no entry for bootstrap in `package.json`). Can you explain why?

**Comment by Tushar98644** [comment]
> another thing, you are using bootstrap in this website, as evident from the line in `_app.js` file
> 
> ```js
>   useEffect(() => {
>     require("bootstrap/dist/js/bootstrap.bundle.min.js");
>   }, []);
> ```
> 
> but you never seem to install the bootstrap packages via npm (no entry for bootstrap in `package.json`). Can you explain why?



> Few improvement suggestions:
> 
> 1. for desktop view, add a margin to the left as it appears to be sticking to the left
> 2. both side margin is needed in mobile view. Might even try to fix aspect ratio of images as they look quite distorted.
>    image
> 3. For dimentions less than 600px(width), the page looks like this:
>    image
>    This issue did not occur during the navbar PR where I checked the hamburger nav, but it is only occuring in this specific page in the website.
> 
> FIx these issues and tell me for another review

fixed everything ....hopefully the navbar won't be causing rouble now.....

**Comment by Tushar98644** [comment]
> another thing, you are using bootstrap in this website, as evident from the line in `_app.js` file
> 
> ```js
>   useEffect(() => {
>     require("bootstrap/dist/js/bootstrap.bundle.min.js");
>   }, []);
> ```
> 
> but you never seem to install the bootstrap packages via npm (no entry for bootstrap in `package.json`). Can you explain why?

actually i forgot to install the package and even after installing the components didn't seem to work ....so i have added the bootstrap cdn link to the head tag

**Comment by aritroCoder** [comment]
Nice work!

**Comment by Tushar98644** [comment]
> Nice work!

now the bootstrap package works ....i mistakely installed wrong package ...committing new changes....

closes #28

**Pull request merged**
