### PR TITLE
signup ui

### PR DESCRIPTION
**Pull request by Tushar98644**
Screenshot 2022-12-16 at 10 48 31 AM

### CODE REVIEW

**Comment by Tushar98644** [comment]
kindly review it @aritroCoder

**Comment by Tushar98644** [comment]
any updates? @aritroCoder

**Comment by aritroCoder** [comment]
> any updates? @aritroCoder

Sorry for the delay, it looks fine. Can you share the mobile view please?

**Comment by Tushar98644** [comment]
> > any updates? @aritroCoder
> 
> Sorry for the delay, it looks fine. Can you share the mobile view please?

Screenshot 2022-12-17 at 11 50 07 PM
yes sure

**Comment by Tushar98644** [comment]
@aritroCoder any updates?

**Comment by aritroCoder** [comment]
> > > any updates? @aritroCoder
> > 
> > 
> > Sorry for the delay, it looks fine. Can you share the mobile view please?
> 
> Screenshot 2022-12-17 at 11 50 07 PM
> 
> yes sure

The arrange ment of the sections seem wired and not visible properly, I think it will be better if in mobile view the sections are a little larger and vertically arranged

**Comment by Tushar98644** [comment]
> > > > any updates? @aritroCoder
> > > 
> > > 
> > > Sorry for the delay, it looks fine. Can you share the mobile view please?
> > 
> > 
> > Screenshot 2022-12-17 at 11 50 07 PM
> > yes sure
> 
> The arrange ment of the sections seem wired and not visible properly, I think it will be better if in mobile view the sections are a little larger and vertically arranged

ok... will make changes by today eod....

**Comment by Tushar98644** [comment]
changes done @aritroCoder 
Screenshot 2022-12-26 at 12 00 15 PM

**Comment by aritroCoder** [comment]
nice!
Accepting your PR

**Comment by aritroCoder** [comment]
closes #19

**Comment by aritroCoder** [comment]
closes #18

**Comment by Tushar98644** [comment]
> nice! Accepting your PR

also corrected the navbar issue....now it doesn't bulge out as in previous images

**Comment by aritroCoder** [comment]
> > nice! Accepting your PR
> 
> also corrected the navbar issue....now it doesn't bulge out as in previous images

It would be better if you can leave the navbar as it is. as I had made the navbar and there is a proper way I will fix that, I dont want the changes to conflict. Other changes are fine

**Comment by Tushar98644** [comment]
> > > nice! Accepting your PR
> > 
> > 
> > also corrected the navbar issue....now it doesn't bulge out as in previous images
> 
> It would be better if you can leave the navbar as it is. as I had made the navbar and there is a proper way I will fix that, I dont want the changes to conflict. Other changes are fine

ok ...reverting the changes

**Comment by Tushar98644** [comment]
> > > nice! Accepting your PR
> > 
> > 
> > also corrected the navbar issue....now it doesn't bulge out as in previous images
> 
> It would be better if you can leave the navbar as it is. as I had made the navbar and there is a proper way I will fix that, I dont want the changes to conflict. Other changes are fine

the changes are not that significant btw....i just converted the font-size and height from px into vw ...it works completely fine now.....

**Comment by Tushar98644** [comment]
@aritroCoder haven't got the points for this issue ...kindly check

**Comment by aritroCoder** [comment]
> @aritroCoder haven't got the points for this issue ...kindly check

given

**Pull request merged**
